# Generated by Django 4.1.8 on 2023-05-02 11:45

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="signin",
            fields=[
                (
                    "id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("Username", models.CharField(max_length=250, unique=True)),
                ("Password", models.CharField(max_length=250, unique=True)),
                ("FaviouriteCity", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name_plural": "Contact",
            },
        ),
    ]
